Repository EASYPEACH/shroop, pull requests merged in 2023-09, with the labels that each got.

#282 Chore: Bank Entity 생성
  backend/src/main/java/com/easypeach/shroop/modules/bank/domain/Bank.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/domain/BankRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
Labels: 백엔드, 개발환경 세팅

#271 Feat: 마이페이지 진입 시 회원 정보를 가져오는 API 구현
  backend/src/docs/asciidoc/auth.adoc
  backend/src/main/java/com/easypeach/shroop/modules/likes/domain/LikeRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/service/LikeService.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/LikeProductInfo.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/MyPageInfoResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
Labels: 기능개발, 백엔드

#285 Feat: 로딩 UI 구현
  frontend/src/App.vue
  frontend/src/api/index.js
  frontend/src/components/ApiLoader.vue
  frontend/src/layouts/default/DefaultLayout.vue
  frontend/src/router/index.js
  frontend/src/store/useLoading.js
Labels: 기능개발, UI/UX, 프론트엔드

#283 Feat: 상품 검색하기 API를 구현한다
  backend/build.gradle
  backend/src/main/java/com/easypeach/shroop/infra/config/QuerydslConfig.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/SearchRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductOneImgResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/SearchProductResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustom.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 기능개발, 백엔드

#289 Fix: 전체 코드 리팩토링 및 정리
  frontend/src/components/Button/LikeButton.vue
  frontend/src/components/Button/NotifyBellButton.vue
  frontend/src/components/Card/ProductCard.vue
  frontend/src/components/Form/PasswordInput.vue
  frontend/src/components/NotifyBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/DeliveryRegistView.vue
  frontend/src/views/EditProileView.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/PhoneAuthView.vue
  frontend/src/views/ProductDetailsView.vue
  frontend/src/views/PurchaseCompleteView.vue
  frontend/src/views/PurchaseRequestView.vue
  frontend/src/views/RegistProductView.vue
  frontend/src/views/ReportView.vue
  frontend/src/views/ReturnRequestView.vue
  frontend/src/views/SignupView.vue
Labels: 프론트엔드, 리팩토링

#295 Refactor: 마이페이지에 추가로 필요한 데이터 dto 추가
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/LikeProductInfo.java
Labels: 기능개발, 백엔드, 리팩토링

#294 Feat: 마이페이지 API 연동
  frontend/src/views/MypageView.vue
Labels: 기능개발, UI/UX, 프론트엔드

#296 Feat: 포인트 충전, 환전 API 구현
  backend/src/main/java/com/easypeach/shroop/modules/bank/domain/Bank.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/domain/BankRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/exception/BankNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/exception/MinusMoneyException.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/PointController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/main/java/com/easypeach/shroop/modules/member/exception/MinusPointException.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/resources/import.sql
  backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/member/controller/PointControllerTest.java
Labels: 기능개발, 백엔드

#292 Refactor: 알림 아이콘을 변경한다
  frontend/src/components/Button/NotifyBellButton.vue
Labels: 프론트엔드, 리팩토링

#298 Feat: 검색 UI 추가 구현
  frontend/src/App.vue
  frontend/src/components/Button/HamburgerButton.vue
  frontend/src/components/Navigation/SideNavigation.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/DefaultLayout.vue
  frontend/src/plugins/vuetify.js
  frontend/src/store/useMobileNav.js
  frontend/src/store/useNotifyList.js
  frontend/src/views/HomeView.vue
  frontend/src/views/PurchaseRequestView.vue
Labels: UI/UX, 프론트엔드

#303 Design: UI 틀어짐 및 오류 수정
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/image/logo-black.png
  frontend/src/assets/image/logo-white.png
  frontend/src/assets/image/logo.png
  frontend/src/assets/image/product-detail-mobile.png
  frontend/src/assets/image/product-detail.png
  frontend/src/assets/image/purchase-mobile.png
  frontend/src/assets/image/purchase.png
  frontend/src/assets/image/white_logo.png
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Button/HamburgerButton.vue
  frontend/src/components/Button/NotifyBellButton.vue
  frontend/src/components/Card/ProductCard.vue
  frontend/src/components/ImageAttach.vue
  frontend/src/components/Navigation/SideNavigation.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/DefaultLayout.vue
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
  frontend/src/store/useNotifyList.js
  frontend/src/views/EditProileView.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/MypageView.vue
  frontend/src/views/ProductDetailsView.vue
Labels: 버그, UI/UX, 프론트엔드

#302 Refactor: 포인트 도입에 따른 거래 로직 수정
  backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/PointController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/ShroopMember.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/LackOfPointException.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/SellerPurchaseException.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/main/resources/import.sql
  backend/src/test/java/com/easypeach/shroop/modules/member/controller/PointControllerTest.java
Labels: 백엔드, 리팩토링

#300 Feat: 계좌 연동하기 API 구현
  backend/src/main/java/com/easypeach/shroop/modules/bank/controller/BankController.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/domain/Bank.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/dto/LinkBankRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
  backend/src/test/java/com/easypeach/shroop/modules/bank/controller/BankControllerTest.java
Labels: 기능개발, 백엔드

#304 Feat: 프론트에 검색하기 API를 연동한다
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
  frontend/src/components/Button/LikeButton.vue
  frontend/src/components/Card/ProductCard.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/store/useSearchProduct.js
  frontend/src/utils/toggleLikesProduct.js
  frontend/src/views/ProductsView.vue
Labels: 기능개발, 프론트엔드, 백엔드

#305 Refactor: 신고하기 기능을 리팩토링한다
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/report/dto/request/ReportRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
  backend/src/test/java/com/easypeach/shroop/modules/report/controller/ReportControllerTest.java
  frontend/src/views/ReportView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#311 Bug: 상태값 변경에 따라 로직 수정
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
Labels: 버그, 백엔드

#307 Feat: 프론트에 구매자정보 조회 API를 연동한다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/BuyerResponse.java
  frontend/src/components/Banner/MypageProductBanner.vue
Labels: 기능개발, 프론트엔드, 백엔드

#313 Bug: 반환값에 대한 변수명 수정에 따라 테스트 코드 수정
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 버그, 백엔드

#317 Fix: s3 cors 오류 해결
  frontend/src/utils/changeUrlToFiles.js
  frontend/src/views/EditProileView.vue
Labels: 버그, 프론트엔드

#319 Refactor: 계좌 연동하기 API 리팩토링, 계좌 생성 API 구현
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/controller/BankController.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/domain/Bank.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/dto/LinkBankRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/exception/AccountMismatchException.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
  backend/src/main/resources/import.sql
Labels: 백엔드, 리팩토링

#320 Refactor: PR에서 푸시 안된 커밋
  backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
Labels: 백엔드, 리팩토링

#321 Feat: AOP 로그 추적기 구현
  backend/build.gradle
  backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserLog.java
  backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserLogDto.java
  backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserLogRepository.java
  backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserTrace.java
  backend/src/main/java/com/easypeach/shroop/infra/aop/log/user/UserTraceAspect.java
  backend/src/main/java/com/easypeach/shroop/infra/security/handler/SecurityAuthenticationSuccessHandler.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/controller/LikeController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/ProfileEditRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/report/controller/ReportController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/DeliveryController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
Labels: 기능개발, 백엔드

#315 Refactor: 결제 로직 수정으로 인해 구매확정, 반품확정 로직을 수정했다.
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 백엔드, 리팩토링

#327 Feat: 포인트 반영 API 프론트 연동 및 API 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/bank/service/BankService.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/MyPageInfoResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/resources/import.sql
  frontend/src/api/modules/patchApi.js
  frontend/src/components/Modal/ChargePointModal.vue
  frontend/src/components/Modal/LinkAccountModal.vue
  frontend/src/views/MypageView.vue
Labels: 기능개발, 프론트엔드, 백엔드, 리팩토링

#325 Refactor: 홈화면 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductOneImgResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
  frontend/src/components/Button/LikeButton.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/main.js
  frontend/src/plugins/index.js
  frontend/src/utils/toggleLikesProduct.js
  frontend/src/views/HomeView.vue
  frontend/src/views/ProductsView.vue
Labels: 버그, 프론트엔드, 백엔드, 리팩토링

#331 Feat: 회원 정보 조회 API 에 등급 점수도 반환하도록 추가
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/MyPageInfoResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/resources/import.sql
Labels: 기능개발, 백엔드

#330 Refactor: 신고 이미지 엔티티에 cascade 설정을 추가했다
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImg.java
Labels: 백엔드, 리팩토링

#334 Refactor: 카테고리명에 유니크 설정을 추가했다
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Category.java
Labels: 백엔드, 리팩토링

#336 Bug: 상품 검색하기 API의 테스트 코드를 수정했다
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 버그, 백엔드

#337 Test: 상품, 카테고리, 좋아요 테스트 코드 작성
  backend/build.gradle
  backend/gradlew
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/category.adoc
  backend/src/docs/asciidoc/likes.adoc
  backend/src/docs/asciidoc/product.adoc
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/CategoryController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Category.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/CategoryRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/MemberResonse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductImgResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/main/resources/static/auth.html
  backend/src/main/resources/static/category.html
  backend/src/main/resources/static/index.html
  backend/src/main/resources/static/likes.html
  backend/src/main/resources/static/product.html
  backend/src/test/java/com/easypeach/shroop/modules/likes/controller/LikeControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/CategoryControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 백엔드, 개발환경 세팅, 테스트

#339 Test: 신고하기 API 테스트 코드를 수정했다
  backend/src/docs/asciidoc/report.adoc
  backend/src/main/resources/static/report.html
  backend/src/test/java/com/easypeach/shroop/modules/report/controller/ReportControllerTest.java
Labels: 백엔드, 리팩토링, 테스트

#343 Feat: 회원 탈퇴 처리 API 구현
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberInfo.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
Labels: 기능개발, 백엔드

#341 Test: 알림 API 테스트 코드를 수정했다
  backend/src/docs/asciidoc/notification.adoc
  backend/src/main/resources/static/notification.html
  backend/src/test/java/com/easypeach/shroop/modules/notification/controller/NotificationControllerTest.java
Labels: 백엔드, 리팩토링, 테스트

#344 Test: 배송 API의 테스트 코드를 수정했다
  backend/src/docs/asciidoc/delivery.adoc
  backend/src/main/resources/static/delivery.html
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/DeliveryControllerTest.java
Labels: 백엔드, 리팩토링, 테스트

#348 Feat: 404페이지를 추가했다
  frontend/src/router/index.js
  frontend/src/views/NotFound.vue
Labels: UI/UX, 프론트엔드

#353 Feat: 회원,인증 관련 테스트 코드 작성
  backend/src/docs/asciidoc/auth.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberSignInRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberSignUpRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/ProfileEditRequest.java
  backend/src/main/resources/static/auth.html
  backend/src/main/resources/static/index.html
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
Labels: 기능개발, 백엔드

#346 Feat: 탈퇴 API 프론트 연동
  frontend/src/views/EditProileView.vue
  frontend/src/views/MypageView.vue
Labels: 기능개발, 프론트엔드

#356 Fix: 이미지 파일이 넘어오지 않을 경우 null 이슈 처리
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
Labels: 버그, 백엔드

#350 Refactor: 상품관련 DTO 코드를 최적화했다
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/MemberResonse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductImgResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 백엔드, 리팩토링

#354 Test: 거래 관련 API 테스트 코드를 수정했다
  backend/src/docs/asciidoc/return.adoc
  backend/src/docs/asciidoc/transaction.adoc
  backend/src/main/resources/static/return.html
  backend/src/main/resources/static/transaction.html
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductReturnControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 백엔드, 리팩토링, 테스트

#360 Refator: 엔티티 연관 관계 Lazy 설정
  backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/controller/MediateController.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/Mediate.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateImg.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/service/MediateService.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/domain/Notification.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturn.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturnImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/BlackList.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImg.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  backend/src/main/resources/import.sql
Labels: 기능개발, 백엔드

#358 Fix: 다른 브라우저에서 로그인 시, 500 에러가 나는 현상 수정
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  frontend/src/App.vue
  frontend/src/store/useCheckLogin.js
Labels: 버그, 프론트엔드, 백엔드

#362 Fix: 상품 응답 DTO 내부에 카테고리 타입 변경
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 버그, 백엔드, 테스트

#367 Refactor: 프론트 코드 최적화
  frontend/src/App.vue
  frontend/src/components/Alert/index.js
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Banner/index.js
  frontend/src/components/Button/HamburgerButton.vue
  frontend/src/components/Button/NotifyBellButton.vue
  frontend/src/components/Button/index.js
  frontend/src/components/Form/PasswordInput.vue
  frontend/src/components/Form/index.js
  frontend/src/components/Modal/ChargePointModal.vue
  frontend/src/components/Modal/LinkAccountModal.vue
  frontend/src/components/Modal/PlainModal.vue
  frontend/src/components/Modal/index.js
  frontend/src/components/ProductCard.vue
  frontend/src/components/SideBar/NotifyBar.vue
  frontend/src/components/SideBar/SideNavigation.vue
  frontend/src/components/SideBar/index.js
  frontend/src/components/Title/index.js
  frontend/src/components/TransactionBadge.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/DefaultLayout.vue
  frontend/src/router/index.js
  frontend/src/store/modules/index.js
  frontend/src/store/modules/useApiLoading.js
  frontend/src/store/modules/useCheckLogin.js
  frontend/src/store/modules/useMobileNav.js
  frontend/src/store/modules/useMypageTab.js
  frontend/src/store/modules/useNotifyList.js
  frontend/src/store/modules/useSearchProduct.js
  frontend/src/store/modules/useShowNotify.js
  frontend/src/store/modules/useUserStore.js
  frontend/src/views/HomeView.vue
  frontend/src/views/MypageView.vue
  frontend/src/views/NotFound.vue
  frontend/src/views/auth/LoginView.vue
  frontend/src/views/auth/PhoneAuthView.vue
  frontend/src/views/auth/SignupView.vue
  frontend/src/views/auth/index.js
  frontend/src/views/mypage/MyPagePurchaseListView.vue
  frontend/src/views/mypage/MyPageSellListView.vue
  frontend/src/views/mypage/MypageEditProfileView.vue
  frontend/src/views/mypage/MypageHomeView.vue
  frontend/src/views/mypage/MypageView.vue
  frontend/src/views/mypage/index.js
  frontend/src/views/product/ProductDetailsView.vue
  frontend/src/views/product/ProductsView.vue
  frontend/src/views/product/RegistProductView.vue
  frontend/src/views/product/index.js
  frontend/src/views/report/ReportView.vue
  frontend/src/views/transaction/DeliveryRegistView.vue
  frontend/src/views/transaction/PurchaseCompleteView.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
  frontend/src/views/transaction/ReturnRequestView.vue
  frontend/src/views/transaction/index.js
Labels: UI/UX, 프론트엔드, 리팩토링

#370 Fix: 라우터 뷰 경로 수정
  frontend/src/views/auth/index.js
  frontend/src/views/mypage/index.js
  frontend/src/views/product/index.js
  frontend/src/views/transaction/index.js
Labels: 버그, 프론트엔드

#364 Refactor: 신고 신청할 경우 신고 받은 사람 정보도 추가하도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
Labels: 백엔드, 리팩토링

#366 Feat: 상품 등록 로직 수정
  backend/src/main/java/com/easypeach/shroop/infra/s3/service/S3UploadService.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportImgService.java
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 백엔드, 리팩토링

#373 Fix: 마이페이지 라우터 경로 수정
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/DeliveryService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 백엔드, 리팩토링

#374 Bug: 상품 전체 조회시 이미지는 대표이지미 하나만 가져오도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
Labels: 버그, 백엔드

#379 Refactor: 예외처리 이름 명확하게 수정
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/NoSuchPhoneAuthException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/PhoneAuthNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/UnAuthorizedAccessException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/repository/PhoneAuthRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/domain/BankRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/exception/BankNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/bank/exception/NoSuchBankException.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/member/exception/MemberNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/member/exception/NoSuchMemberException.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/exception/CategoryNotFoundException.java
  backend/src/main/java/com/easypeach/shroop/modules/product/exception/NoSuchCategoryException.java
  backend/src/main/java/com/easypeach/shroop/modules/product/exception/ProductException.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/CategoryRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
Labels: 백엔드, 리팩토링

#377 Feat: 차단,탈퇴 계정은 로그인 하지 못하도록 수정
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/security/handler/SecurityAuthenticationFailureHandler.java
  backend/src/main/java/com/easypeach/shroop/infra/security/handler/SecurityAuthenticationSuccessHandler.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/LoginFailResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/main/resources/import.sql
Labels: 기능개발, 백엔드

#390 Fix: 예외처리 코드 수정 안된부분을 다시 적용
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
Labels: 버그, 백엔드

#387 Feat: 차단,탈퇴한 계정 실패 사유 로그인창에 노출
  frontend/src/App.vue
  frontend/src/views/auth/LoginView.vue
Labels: 기능개발, 프론트엔드

#391 Fix: 프로필 수정 시 이미지가 안나오는 현상 수정
  frontend/src/router/index.js
  frontend/src/views/auth/PhoneAuthView.vue
  frontend/src/views/mypage/MypageEditProfileView.vue
Labels: 버그, 프론트엔드, 백엔드

#385 Refactor: value-bind 잘못된 것 수정
  frontend/src/components/Form/PasswordInput.vue
  frontend/src/components/Form/PhoneInput.vue
Labels: 버그, 프론트엔드, 리팩토링

#393 Fix: 마이페이지 판매내역 페이지네이션 액티브 안되는 오류 수정
  frontend/src/views/mypage/MyPagePurchaseListView.vue
  frontend/src/views/mypage/MyPageSellListView.vue
  frontend/src/views/mypage/MypageEditProfileView.vue
  frontend/src/views/mypage/MypageHomeView.vue
Labels: 버그, 프론트엔드, 리팩토링

#401 Refactor: 더미 데이터를 수정했다
  backend/src/main/resources/import.sql
Labels: 백엔드, 리팩토링

#404 Refactor: 사용하지 않고 있는 테이블을 제거했다
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/BlackList.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/BlackListRepository.java
Labels: 백엔드, 리팩토링

#398 Feat: 사용자의 이미지URL, 등급 점수를 가져올 수 있도록 DTO 수정한다
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 백엔드, 리팩토링

#397 Fix: 로그인 안되었을때 계속 새로고침 되는 오류를 수정
  frontend/src/App.vue
Labels: 버그, 프론트엔드

#409 Fix: 상품 조회 테스트 코드를 수정한다
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductControllerTest.java
Labels: 버그, 백엔드

#406 Feat: 마이페이지 점수별 등급이 노출되도록 수정한다
  frontend/src/views/mypage/MypageHomeView.vue
Labels: 프론트엔드, 리팩토링

#405 Fix: 상품 상세 페이지 결함 이미지 크기 조정
  frontend/src/components/Modal/ImageThumbModal.vue
  frontend/src/components/Modal/index.js
  frontend/src/views/product/ProductDetailsView.vue
Labels: 버그, UI/UX, 프론트엔드, 리팩토링

#411 Fix: 카테고리 엔티티를 DTO로 변경한다
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/LikeProductInfo.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
Labels: 버그, 백엔드

#414 Refactor: 거래 리팩토링을 한다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  frontend/src/views/transaction/PurchaseCompleteView.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
Labels: 백엔드, 리팩토링

#413 Fix: 프로필 수정 로직을 수정한다
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
Labels: 버그, 백엔드

#416 Refactor: 모바일 환경에서의 배너 크기 조정
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/ProductCard.vue
  frontend/src/main.js
  frontend/src/plugins/index.js
Labels: UI/UX, 프론트엔드, 리팩토링

#417 Feat: pwa 웹앱 설정
  frontend/dev-dist/registerSW.js
  frontend/dev-dist/sw.js
  frontend/dev-dist/workbox-5357ef54.js
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/icons/icon-192x192.png
  frontend/public/icons/icon-256x256.png
  frontend/public/icons/icon-384x384.png
  frontend/public/icons/icon-512x512.png
  frontend/public/manifest.json
  frontend/src/styles/global.style.css
  frontend/src/sw.js
  frontend/vite.config.js
Labels: 기능개발, 프론트엔드

#419 Refactor: 모바일 환경에서 알림 버튼 추가
  frontend/src/components/Button/HamburgerButton.vue
  frontend/src/components/Button/NotifyBellButton.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/plugins/vuetify.js
  frontend/src/store/modules/useShowNotify.js
  frontend/src/views/mypage/MypageHomeView.vue
Labels: UI/UX, 프론트엔드

#424 Fix:service-worker의 설정을 변경했다
  frontend/dev-dist/sw.js
  frontend/dev-dist/workbox-5357ef54.js
  frontend/index.html
  frontend/src/main.js
  frontend/src/service-worker.js
  frontend/src/sw.js
  frontend/vite.config.js
Labels: 버그, 기능개발, 프론트엔드

#422 Refactor: 구매 확정되면 판매자의 회원등급이 상승되도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 백엔드, 리팩토링

#431 Fix: 앱 아이콘 변경
  frontend/index.html
  frontend/public/icons/icon-128x128.png
  frontend/public/icons/icon-144x144.png
  frontend/public/icons/icon-152x152.png
  frontend/public/icons/icon-192x192.png
  frontend/public/icons/icon-256x256.png
  frontend/public/icons/icon-384x384.png
  frontend/public/icons/icon-48x48.png
  frontend/public/icons/icon-512x512.png
  frontend/public/icons/icon-72x72.png
  frontend/public/icons/icon-96x96.png
  frontend/public/manifest.json
Labels: 버그, 기능개발, 프론트엔드

#433 Fix: 코드 오타를 수정한다
  frontend/public/manifest.json
  package-lock.json
Labels: 버그, 기능개발, 프론트엔드

#432 Refactor: 더미데이터를 수정했다
  backend/src/main/resources/import.sql
Labels: 백엔드, 리팩토링

#427 Refactor: 운송장번호는 숫자만 입력가능하도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/DeliveryController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/DeliveryRequest.java
  frontend/src/components/Form/data/formRules.js
  frontend/src/views/transaction/DeliveryRegistView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#435 Fix: 회원가입 유효성, 중복 체크가 완료되어야 다음 버튼이 활성화되도록 수정
  frontend/src/components/Form/PhoneInput.vue
  frontend/src/views/auth/SignupView.vue
Labels: 버그, 프론트엔드

#441 Bug: 상품 검색 조회 시 좋아요가 잘못나오는 부분 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
Labels: 버그, 백엔드

#437 Refactor: 상품 전체 조회 요청하는 부분을 수정했다.
  frontend/src/views/product/ProductsView.vue
Labels: 프론트엔드, 리팩토링

#438 Refactor: 마이페이지 구매내역 조회 페이징으로 리팩토링을 했다
  backend/src/docs/asciidoc/transaction.adoc
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/main/resources/static/auth.html
  backend/src/main/resources/static/category.html
  backend/src/main/resources/static/delivery.html
  backend/src/main/resources/static/likes.html
  backend/src/main/resources/static/member.html
  backend/src/main/resources/static/notification.html
  backend/src/main/resources/static/product.html
  backend/src/main/resources/static/report.html
  backend/src/main/resources/static/return.html
  backend/src/main/resources/static/transaction.html
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryControllerTest.java
  frontend/index.html
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/views/mypage/MyPagePurchaseListView.vue
  frontend/src/views/mypage/MyPageSellListView.vue
Labels: 프론트엔드, 백엔드, 리팩토링, 테스트

#447 Fix: 마이페이지 삭제하기 API 연동
  frontend/src/App.vue
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/views/mypage/MyPagePurchaseListView.vue
  frontend/src/views/mypage/MyPageSellListView.vue
  frontend/src/views/mypage/MypageEditProfileView.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#444 Refactor: 로그인 실패시 패스워드 초기화를 하도록 한다
  frontend/src/views/auth/LoginView.vue
Labels: 프론트엔드, 리팩토링

#450 Refactor: 구매취소 시 구매자에게 포인트 환불되도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 백엔드, 리팩토링

#449 Fix: 모바일 환경에서의 모션 수정
  frontend/src/views/HomeView.vue
Labels: 프론트엔드, 리팩토링

#452 Refactor: 알림 클릭시 페이지 이동 로직을 수정했다
  frontend/src/components/SideBar/NotifyBar.vue
Labels: 프론트엔드, 리팩토링

#460 Refactor: 모바일 환경에서의 UI 틀어짐 수정
  frontend/src/components/Button/HamburgerButton.vue
  frontend/src/components/ProductCard.vue
  frontend/src/components/Title/ProductTitle.vue
  frontend/src/layouts/ContentLayout.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/DefaultFooter.vue
  frontend/src/layouts/default/DefaultLayout.vue
  frontend/src/layouts/default/MobileAppBar.vue
  frontend/src/views/product/ProductDetailsView.vue
  frontend/src/views/report/ReportView.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#462 Refactor: 계좌 연동 리팩토링을 했다
  backend/src/main/java/com/easypeach/shroop/modules/bank/dto/LinkBankRequest.java
  frontend/src/components/Modal/LinkAccountModal.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#454 Refactor: 신고하기와 중재하기를 구분했다
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionStatus.java
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/consts/status.js
  frontend/src/router/index.js
  frontend/src/views/report/ReportView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#467 Refactor: 계좌연동 및 결제창 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/TransactionCreateRequest.java
  frontend/src/components/Modal/LinkAccountModal.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#459 Feat: 휴대전화인증 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/domain/PhoneAuth.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/PhoneAuthUUID.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/AuthFailCountException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/AuthTimeOutException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthCountService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  frontend/package-lock.json
  frontend/src/views/auth/PhoneAuthView.vue
  frontend/src/views/auth/SignupView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#470 Refactor: 유효성 검사 추가를 했다
  frontend/src/components/Form/data/formRules.js
  frontend/src/components/Modal/ChargePointModal.vue
  frontend/src/components/Modal/LinkAccountModal.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
Labels: 프론트엔드, 리팩토링

#471 Style: UX의 개선
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Button/LikeButton.vue
  frontend/src/components/ImageAttach.vue
  frontend/src/components/ProductCard.vue
  frontend/src/components/ProductSwiper.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/DefaultLayout.vue
  frontend/src/layouts/default/MobileAppBar.vue
  frontend/src/plugins/vuetify.js
  frontend/src/styles/global.style.css
  frontend/src/views/HomeView.vue
  frontend/src/views/mypage/MypageEditProfileView.vue
  frontend/src/views/mypage/MypageHomeView.vue
  frontend/src/views/mypage/MypageView.vue
  frontend/src/views/product/ProductDetailsView.vue
  frontend/src/views/product/ProductsView.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
  package-lock.json
Labels: UI/UX, 프론트엔드

#473 Fix: 본인 인증 테스트 코드 수정
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
Labels: 버그, 백엔드, 테스트

#477 Fix: 인증 제한 시간 0으로 나오는 현상 수정
  frontend/src/views/auth/PhoneAuthView.vue
Labels: 버그, 프론트엔드

#479 Refactor: readme를 수정했다
  README.md
Labels: 문서작성

#484 Feat: 회원가입 동의 약관 샘플 추가
  frontend/package-lock.json
  frontend/src/components/Form/AgreementDialog.vue
  frontend/src/components/Form/data/usageRules.js
Labels: 프론트엔드, 리팩토링

#482 Fix: 구매확정, 구매취소, 반품확정 확인 클릭 시 모달이 사라지도록 수정했다
  frontend/src/components/Banner/MypageProductBanner.vue
Labels: 프론트엔드, 리팩토링

#486 Refactor: 인증 제한 시간 2분으로 수정
  frontend/src/views/auth/PhoneAuthView.vue
Labels: 프론트엔드, 리팩토링

#488 Refactor: 인증 제한 시간 수정
  frontend/src/views/auth/PhoneAuthView.vue
Labels: 프론트엔드, 리팩토링

#489 Refactor: 문자 발송 제한을 해제했다
  backend/src/main/java/com/easypeach/shroop/infra/phone/NaverPhoneAuthClient.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/service/NotificationService.java
  backend/src/main/resources/import.sql
Labels: 프론트엔드, 백엔드, 리팩토링

#490 Test: 로그인,회원가입, 상품 단위테스트
  frontend/cypress.config.js
  frontend/cypress/e2e/jsconfig.json
  frontend/cypress/e2e/loginTest.cy.js
  frontend/cypress/e2e/productTest.cy.js
  frontend/cypress/e2e/signupTest.cy.js
  frontend/cypress/e2e/testImage/macbook1.jpeg
  frontend/cypress/e2e/testImage/macbook2.jpeg
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.js
  frontend/cypress/support/component-index.html
  frontend/cypress/support/component.js
  frontend/cypress/support/e2e.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/auth/LoginView.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
  frontend/vitest.config.js
Labels: 프론트엔드, 테스트

#494 Fix: 상품 전체 조회 시 좋아요 개수만큰 중복 조회되는 오류를 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
  backend/src/main/resources/import.sql
Labels: 버그, 백엔드

#496 Refactor: 좋아요 기능 동시성을 리팩토링했다
  backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
Labels: 백엔드, 리팩토링

#492 Design: 마이페이지 컨텐츠 상단 여백 제거
  frontend/src/components/Modal/ImageThumbModal.vue
  frontend/src/components/ProductSwiper.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/mypage/MyPagePurchaseListView.vue
  frontend/src/views/mypage/MyPageSellListView.vue
  frontend/src/views/mypage/MypageEditProfileView.vue
  frontend/src/views/mypage/MypageHomeView.vue
  frontend/src/views/product/ProductDetailsView.vue
Labels: UI/UX, 프론트엔드

#497 Fix: 상품 상세페이지 버튼 오류 수정
  frontend/src/views/product/ProductDetailsView.vue
Labels: 버그, UI/UX, 프론트엔드

#500 Refactor: 좋아요 기능 동시성 이슈를 수정했다
  backend/src/main/java/com/easypeach/shroop/infra/aop/likes/Retry.java
  backend/src/main/java/com/easypeach/shroop/infra/aop/likes/RetryAspect.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/service/LikeService.java
Labels: 백엔드, 리팩토링

#501 Design: 계좌연동 UI 변경
  frontend/src/components/Modal/ChargePointModal.vue
  frontend/src/components/Modal/LinkAccountModal.vue
  frontend/src/views/HomeView.vue
Labels: UI/UX, 프론트엔드

#503 Fix: restdocs 경로 수정
  backend/src/docs/asciidoc/index.html
  backend/src/main/resources/static/auth.html
  backend/src/main/resources/static/category.html
  backend/src/main/resources/static/delivery.html
  backend/src/main/resources/static/index.html
  backend/src/main/resources/static/likes.html
  backend/src/main/resources/static/member.html
  backend/src/main/resources/static/notification.html
  backend/src/main/resources/static/product.html
  backend/src/main/resources/static/report.html
  backend/src/main/resources/static/return.html
  backend/src/main/resources/static/transaction.html
Labels: 문서작성, 백엔드, 개발환경 세팅

#509 Test: 결제하기 단위 테스트
  frontend/cypress/e2e/transactionTest.cy.js
  frontend/src/components/Modal/ChargePointModal.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
Labels: 프론트엔드, 테스트

#507 Refactor: 인증 문자 메세지 내용을 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/service/NotificationService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 백엔드, 리팩토링

#505 Refactor: 회원 수정페이지에서 비밀번호 숨기기 기능 수정했다
  frontend/src/views/mypage/MypageEditProfileView.vue
Labels: 프론트엔드, 리팩토링

#513 Fix: 스와이퍼 높이 수정
  frontend/src/components/ProductSwiper.vue
Labels: UI/UX, 프론트엔드

#515 Test: 좋아요 동시성 테스트 코드를 작성한다
  backend/src/test/java/com/easypeach/shroop/concurrency/ProductConcurrencyTest.java
Labels: 백엔드, 테스트

#516 Feat: 등급 점수 제한을 100점으로 제한한다
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/test/java/com/easypeach/shroop/modules/member/domain/MemberTest.java
Labels: 백엔드, 리팩토링

#519 Refactor: 포인트 리팩토링을 한다
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/PointController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
Labels: 버그, 백엔드, 리팩토링

#520 Refactor: 차단/탈퇴된 유저의 게시물은 안보이도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepositoryCustomImpl.java
Labels: 백엔드, 리팩토링

#522 Refactor: 좋아요 테스트 후 상품 삭제하도록 수정
  backend/src/main/java/com/easypeach/shroop/infra/aop/likes/RetryAspect.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/test/java/com/easypeach/shroop/concurrency/ProductConcurrencyTest.java
Labels: 백엔드, 리팩토링

#524 Test: 마이페이지 조회 수정 테스트
  frontend/cypress.config.js
  frontend/cypress/e2e/eidtProfileTest.cy.js
  frontend/cypress/e2e/loginTest.cy.js
  frontend/cypress/e2e/mypageTest.cy.js
  frontend/cypress/e2e/testImage/profile.png
  frontend/cypress/e2e/transactionTest.cy.js
Labels: 프론트엔드, 테스트

#526 Refactor: 포인트 테스트 리팩토링을 한다
  backend/src/test/java/com/easypeach/shroop/modules/member/controller/PointControllerTest.java
Labels: 백엔드, 테스트

#529 Refactor: 포인트 및 계좌 리팩토링
  frontend/src/components/Modal/LinkAccountModal.vue
  frontend/src/views/mypage/MypageHomeView.vue
Labels: 프론트엔드, 리팩토링

#531 Refactor: 마이페이지에서 회원 정보 DTO 를 수정한다
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/MyPageInfoResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/ProfileEditRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
Labels: 백엔드, 리팩토링

#534 Feat: 반품 조회 API를 구현했다
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductReturnController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturn.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturnImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductReturnImgResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductReturnResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnImgRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
Labels: 기능개발, 백엔드

#538 Feat: 반품 요청 거부 API를 구현했다
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductReturnController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturnImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionStatus.java
Labels: 기능개발, 백엔드

#542 Refactor: dto 수정
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
Labels: 백엔드, 리팩토링

#544 Refactor: 휴대전화인증 제한 시간 추가
  frontend/package-lock.json
  frontend/src/views/mypage/MypageEditProfileView.vue
Labels: 프론트엔드, 리팩토링

#540 Refactor: 배송 등록 시 운송장번호 중복 검사하도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/DuplicateTrackingNumberException.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/DeliveryService.java
Labels: 기능개발, 백엔드

#545 Feat: 반품 거부 기능에 알림 추가했다
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
Labels: 백엔드, 리팩토링

#548 Refactor: 개인정보수정 화면에서 로그인 아이디가 보이도록 DTO 수정
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/ProfileEditForm.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/MemberControllerTest.java
Labels: 백엔드, 리팩토링

#555 Refactor: 글자수 제한 기능을 추가했다
  frontend/src/components/Form/CustomTextArea.vue
  frontend/src/components/Form/data/formRules.js
  frontend/src/views/auth/LoginView.vue
  frontend/src/views/product/RegistProductView.vue
  frontend/src/views/report/ReportView.vue
  frontend/src/views/transaction/DeliveryRegistView.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
Labels: 버그, UI/UX, 프론트엔드

#551 Refactor: 거래상태에 따른 마이페이지의 버튼 노출 조건을 조정했다
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/consts/dummy.js
  frontend/src/consts/status.js
  frontend/src/views/mypage/MypageEditProfileView.vue
Labels: 버그, 프론트엔드

#553 Refactor: 반품 관련 상세페이지를 추가하고 반품 처리를 한다
  frontend/src/router/index.js
  frontend/src/views/transaction/ReturnRequestResultView.vue
  frontend/src/views/transaction/index.js
Labels: UI/UX, 프론트엔드, 리팩토링

#557 Refactor: 구매취소가 되지 않는 오류를 수정했다
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/views/mypage/MypageEditProfileView.vue
  frontend/src/views/transaction/PurchaseCompleteView.vue
Labels: 버그, 프론트엔드, 리팩토링

#559 Refactor: 이미지 최적화를 진행했다
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ImageAttach.vue
  frontend/src/utils/changeUrlToFiles.js
  frontend/src/utils/compressImage.js
  frontend/src/utils/index.js
  frontend/src/views/mypage/MypageEditProfileView.vue
  frontend/src/views/product/RegistProductView.vue
  frontend/src/views/report/ReportView.vue
  frontend/src/views/transaction/PurchaseRequestView.vue
  frontend/src/views/transaction/ReturnRequestView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#561 Fix: 이미지 압축 조건문을 삭제했다
  frontend/src/utils/compressImage.js
Labels: 버그, 프론트엔드

#564 Test: 이미지 압축 결과 테스트 콘솔
  frontend/src/utils/compressImage.js
Labels: 프론트엔드, 테스트

#565 Fix: 이미지 압축 조건 수정
  frontend/src/utils/compressImage.js
Labels: 프론트엔드, 리팩토링

#567 Fix: 이미지 압축 조건 변경
  frontend/src/utils/compressImage.js
Labels: 프론트엔드, 리팩토링

#571 Fix: 아이폰 이미지 확장자 변경 라이브러리 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utils/compressImage.js
Labels: 버그, 프론트엔드

#572 Fix: 이미지 압축 비율 변경
  frontend/src/utils/compressImage.js
Labels: 버그, 프론트엔드

#573 Feat/558 compress image fe be
  frontend/src/utils/compressImage.js
Labels: 버그, 프론트엔드

#575 Design: 홈화면에 소개 내용을 수정했다
  frontend/src/assets/image/product-detail-mobile.png
  frontend/src/assets/image/product-detail.png
  frontend/src/assets/image/purchase-mobile.png
  frontend/src/assets/image/purchase.png
  frontend/src/views/HomeView.vue
Labels: UI/UX, 프론트엔드

#568 Refactor: 결제하기 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  frontend/src/views/transaction/PurchaseRequestView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#577 Design: 파비콘 아이콘 변경
  frontend/public/favicon.ico
  frontend/public/icons/icon-128x128.png
  frontend/public/icons/icon-144x144.png
  frontend/public/icons/icon-152x152.png
  frontend/public/icons/icon-192x192.png
  frontend/public/icons/icon-384x384.png
  frontend/public/icons/icon-48x48.png
  frontend/public/icons/icon-512x512.png
  frontend/public/icons/icon-72x72.png
  frontend/public/icons/icon-96x96.png
Labels: 프론트엔드

#579 Feat/576 favicon fe
  frontend/public/manifest.json
Labels: 프론트엔드

#580 Fix:아이콘 설정 변경
  frontend/index.html
  frontend/public/manifest.json
Labels: 프론트엔드

#582 Refactor: 모바일 화면에서 구매하기 UI 틀어짐을 수정했다
  frontend/src/components/CautionBlock.vue
  frontend/src/styles/global.style.css
  frontend/src/views/HomeView.vue
  frontend/src/views/product/ProductDetailsView.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#584 Fix: 구매자 정보보기 모달 위치 수정
  frontend/src/components/Modal/BuyerInfoModal.vue
Labels: UI/UX, 프론트엔드

#586 Chore: s3 주소를 변경했다
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/resources/import.sql
  frontend/package.json
Labels: 인프라, 개발환경 세팅
