Repository EASYPEACH/shroop, pull requests merged in 2023-08, with the labels that each got.

#14 chore: 백엔드 프로젝트 셋업
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/easypeach/backend/ShroopApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/easypeach/backend/ShroopApplicationTests.java
Labels: 백엔드, 개발환경 세팅

#11 chore: 프론트 프로젝트 셋업
  frontend/.browserslistrc
  frontend/.editorconfig
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/image/logo.png
  frontend/src/components/HelloWorld.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Default.vue
  frontend/src/layouts/default/View.vue
  frontend/src/main.js
  frontend/src/plugins/index.js
  frontend/src/plugins/vuetify.js
  frontend/src/plugins/webfontloader.js
  frontend/src/router/index.js
  frontend/src/store/app.js
  frontend/src/store/index.js
  frontend/src/styles/global.style.css
  frontend/src/styles/settings.scss
  frontend/src/views/Home.vue
  frontend/vite.config.js
Labels: 프론트엔드, 개발환경 세팅

#16 chore: 백엔드 메인프레임 구축
  backend/src/main/java/com/easypeach/shroop/ShroopApplication.java
  backend/src/main/java/com/easypeach/shroop/infra/config/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/like/controller/LikeController.java
  backend/src/main/java/com/easypeach/shroop/modules/like/domain/Like.java
  backend/src/main/java/com/easypeach/shroop/modules/like/domain/LikeRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/like/service/LikeService.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/controller/MediateController.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/Mediate.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/service/MediateService.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberSignInRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/MemberSignUpRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/controller/NotificationController.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/service/NotificationService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/main/java/com/easypeach/shroop/modules/report/controller/ReportController.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/BlackList.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/BlackListRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportRepostiory.java
  backend/src/main/java/com/easypeach/shroop/modules/report/dto/ReportRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/TransactionCreateRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/test/java/com/easypeach/shroop/ShroopApplicationTests.java
Labels: 백엔드, 개발환경 세팅

#18 design: header, footer ui 구현
  frontend/.vite/deps_temp_bfa5ef5e/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/assets/image/logo.png
  frontend/src/components/Footer.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/components/NotificationCard.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Default.vue
  frontend/src/layouts/default/View.vue
  frontend/src/plugins/vuetify.js
  frontend/src/styles/global.style.css
Labels: UI/UX, 프론트엔드

#23 refactor: 상단 타이틀 영문에서 한글로 수정
  frontend/index.html
  frontend/src/layouts/default/AppBar.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#21 feat: ORM 세팅
  backend/.gitignore
  backend/src/main/java/com/easypeach/shroop/modules/like/domain/Like.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/Mediate.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateImg.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/domain/Notification.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Category.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Grade.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/BlackList.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImg.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Delivery.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionStatus.java
  backend/src/main/resources/application.properties
Labels: 백엔드, 개발환경 세팅

#28 Chore: prettier 세팅 및 포맷
  frontend/.eslintrc.js
  frontend/.prettierrc
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/plugins/index.js
  frontend/src/store/app.js
  frontend/src/store/index.js
  frontend/src/styles/global.style.css
  frontend/src/views/Home.vue
  frontend/vite.config.js
Labels: 프론트엔드, 개발환경 세팅

#26 Design: 로그인 페이지 UI 구현
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/components/Form/PasswordInput.vue
  frontend/src/components/Form/data/formRules.js
  frontend/src/components/Title.vue
  frontend/src/plugins/vuetify.js
  frontend/src/views/Login.vue
Labels: UI/UX, 프론트엔드

#31 Refactor: footer,layout 여백을 조정한다
  frontend/src/components/Footer.vue
  frontend/src/layouts/default/View.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#34 Design: 회원가입 페이지 UI 구현
  frontend/src/components/Form/AgreementCheckBox.vue
  frontend/src/components/Form/AgreementDialog.vue
  frontend/src/components/Form/PhoneInput.vue
  frontend/src/components/Form/data/formRules.js
  frontend/src/components/Form/data/usageRules.js
  frontend/src/components/ProductCardMain.vue
  frontend/src/components/Title.vue
  frontend/src/consts/agree.js
  frontend/src/router/index.js
  frontend/src/views/Signup.vue
Labels: UI/UX, 프론트엔드

#36 Design: 메인페이지 UI 구현
  frontend/src/assets/image/white_logo.png
  frontend/src/views/Home.vue
  frontend/src/views/RegisterProduct.vue
Labels: UI/UX, 프론트엔드

#35 Chore: 백엔드 코드 컨벤션을 설정한다
  backend/rule-config/naver-checkstyle-rules.xml
  backend/rule-config/naver-checkstyle-suppressions.xml
  backend/rule-config/naver-intellij-formatter.xml
Labels: 백엔드, 개발환경 세팅

#30 Feat: JWT 기반 인증인가 구현 (회원가입,로그인)
  backend/build.gradle
  backend/src/docs/asciidoc/auth.adoc
  backend/src/main/java/com/easypeach/shroop/infra/config/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/JwtAuthFilter.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/domain/SecurityMember.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignInRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignUpRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/AccessTokenResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/SignUpCompletedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/InvalidTokenException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/JwtTokenProvider.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/dto/ErrorResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
Labels: 기능개발, 백엔드

#45 fix: CORS를 설정한 WebConfig를 빈으로 등록
  backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
Labels: 버그, 백엔드

#43 Feat: 게시글 카드형 수정
  frontend/src/components/ProductCardMain.vue
  frontend/src/views/Home.vue
Labels: UI/UX, 프론트엔드

#40 Feat:휴대폰 인증 시그니처 생성
  backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthService.java
Labels: 기능개발, 백엔드

#48 Refactor: 시큐리티 리팩토링 작업
  backend/src/main/java/com/easypeach/shroop/infra/config/EncoderConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/AuthExceptionHandlerFilter.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/JwtAuthFilter.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/MemberNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/JwtTokenProvider.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/SecurityMemberService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
Labels: 기능개발, 백엔드, 리팩토링

#50 Refactor: 코드 컨벤션 적용
  backend/src/main/java/com/easypeach/shroop/infra/config/EncoderConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/AuthExceptionHandlerFilter.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/JwtAuthFilter.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/domain/SecurityMember.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignInRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignUpRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/AccessTokenResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/SignUpCompletedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/InvalidTokenException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/MemberNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/JwtTokenProvider.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/SecurityMemberService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/dto/ErrorResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/like/domain/Like.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/Mediate.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateImg.java
  backend/src/main/java/com/easypeach/shroop/modules/mediate/domain/MediateStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/domain/Notification.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Category.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Grade.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/BlackList.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImg.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Delivery.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
Labels: 백엔드, 리팩토링

#53 Feat: 로그인된 사용자의 정보를 참조하는 기능 구현
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/JwtAuthFilter.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/JwtTokenProvider.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/support/LoginMember.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/support/LoginMemberId.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
Labels: 기능개발, 백엔드

#54 Refactor: 게시글 카드형 수정한다
  frontend/src/components/ProductCardMain.vue
  frontend/src/views/Home.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#65 Feature: router 경로 변경 및 lazy load 옵션을 제거한다
  frontend/src/router/index.js
Labels: 기능개발, 프론트엔드

#63 Refactor: form 태그와 submit handler를 추가했다
  frontend/src/views/Login.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#62 Refactor: footer의 위치를 Layout 폴더로 이동했다
  frontend/src/layouts/default/Default.vue
  frontend/src/layouts/default/Footer.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#60 Refactor: Header에 회원가입 버튼을 추가했다
  frontend/src/layouts/default/AppBar.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#66 Chore: eslint/prettier 재설정
  frontend/.eslintrc.js
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/components/Form/PasswordInput.vue
  frontend/src/components/ProductTitle.vue
  frontend/src/main.js
  frontend/src/plugins/vuetify.js
Labels: 프론트엔드, 개발환경 세팅

#56 Feat: 상품 상세페이지 추가
  frontend/src/router/index.js
  frontend/src/views/ProductDetails.vue
Labels: UI/UX, 프론트엔드

#70 design: 상품 등록 UI 구현
  frontend/src/components/Alert/InfoAlert.vue
  frontend/src/components/Alert/WarnAlert.vue
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/components/Form/data/formRules.js
  frontend/src/components/GuideText.vue
  frontend/src/components/ImageAttach.vue
  frontend/src/components/ProductTitle.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/utils/changeFiles.js
  frontend/src/utils/deleteImage.js
  frontend/src/views/RegistProductView.vue
Labels: 기능개발, UI/UX, 프론트엔드

#75 Feat: Dockerfile 생성
  backend/Dockerfile
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
Labels: 백엔드, 개발환경 세팅

#76 Chore: dockerize file 생성
  frontend/Dockerfile
  frontend/package.json
Labels: 기능개발, 프론트엔드, 인프라, 개발환경 세팅

#77 Test: jenkins 배포 test
  frontend/README.md
Labels: 인프라, 테스트

#78 [backend] Test: jenkins test
  backend/README.md
Labels: 인프라, 테스트

#79 Test: scm ci skip test
  backend/README.md
Labels: 인프라, 테스트

#80 [backend] Test: scm ci
  backend/README.md
Labels: 인프라, 테스트

#82 Design: mypage ui 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/image/basicProfile.jpeg
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Button/MiniButton.vue
  frontend/src/components/Modal/BuyerInfoModal.vue
  frontend/src/components/Modal/ChargePointModal.vue
  frontend/src/components/Modal/PlainModal.vue
  frontend/src/consts/delivery.js
  frontend/src/layouts/ContentLayout.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/plugins/vuetify.js
  frontend/src/router/index.js
  frontend/src/views/MypageView.vue
Labels: UI/UX, 프론트엔드

#96 Fix: vue-fragment package 제거
  frontend/package-lock.json
  frontend/package.json
Labels: 버그, 프론트엔드, 인프라

#92 Design: 신고 접수 UI 구현
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Button/SubmitButton.vue
  frontend/src/components/Form/CustomTextArea.vue
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/components/Form/data/formRules.js
  frontend/src/components/ImageAttach.vue
  frontend/src/components/Title/ProductTitle.vue
  frontend/src/router/index.js
  frontend/src/utils/changeFiles.js
  frontend/src/utils/deleteImage.js
  frontend/src/views/ReportView.vue
Labels: UI/UX, 프론트엔드

#99 Refactor: 유틸 함수들 하나의 index.js 파일에 통합
  frontend/src/utils/changeFiles.js
  frontend/src/utils/changeImageToData.js
  frontend/src/utils/deleteImage.js
  frontend/src/utils/index.js
Labels: 프론트엔드, 리팩토링

#97 Design: 반품신청하기 페이지 UI 구현
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/views/ReturnRequestView.vue
Labels: UI/UX, 프론트엔드

#101 Refactor: 상품 등록 페이지 변경된 util 함수 설정대로 수정
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/views/RegistProductView.vue
Labels: UI/UX, 프론트엔드

#103 Refactor: 변경된 util 함수 이름으로 import 수정
  frontend/src/views/ReportView.vue
  frontend/src/views/ReturnRequestView.vue
Labels: UI/UX, 프론트엔드

#100 Feat: 전체 상품 리스트 UI 구현
  frontend/src/views/HomeView.vue
  frontend/src/views/ProductsView.vue
Labels: UI/UX, 프론트엔드

#106 Chore: 라우터 경로 추가
  frontend/.eslintrc.js
  frontend/src/router/index.js
Labels: 프론트엔드, 개발환경 세팅

#109 Design: 배송등록 페이지 UI 구현
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Title/ProductTitle.vue
  frontend/src/router/index.js
  frontend/src/views/DeliveryRegistView.vue
  frontend/src/views/MypageView.vue
Labels: UI/UX, 프론트엔드

#107 Feat: 프로필 수정 화면 UI 작업 완료
  frontend/src/components/Button/SubmitButton.vue
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/views/EditProileView.vue
Labels: UI/UX, 프론트엔드

#108 Feat: 상품 결제 페이지 UI 구현 완료
  frontend/src/components/Button/MiniButton.vue
  frontend/src/components/CautionBlock.vue
  frontend/src/views/ProductDetailsView.vue
  frontend/src/views/PurchaseRequestView.vue
Labels: UI/UX, 프론트엔드

#111 Fix: 체크박스 컴포넌트에 데이터 바인딩 잘못 된것 해결
  frontend/src/components/Form/AgreementCheckBox.vue
Labels: 버그, 프론트엔드

#112 Refactor: 신고접수 게시물 제목 일반 텍스트로 변경
  frontend/src/router/index.js
  frontend/src/views/ReportView.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#113 Design: 알림 UI 재구현
  frontend/src/components/Card/NotificationCard.vue
  frontend/src/components/NotifyBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/DefaultLayout.vue
  frontend/src/store/app.js
  frontend/src/store/index.js
  frontend/src/store/useShowNotify.js
  frontend/src/styles/global.style.css
Labels: UI/UX, 프론트엔드

#115 Fix: 컴포넌트 라우터 임포트 방식 변경
  frontend/src/router/index.js
Labels: 버그, UI/UX, 프론트엔드

#117 Refactor: 전체 페이지 반응형 적용 및 리팩토링
  frontend/src/App.vue
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Button/LikeButton.vue
  frontend/src/components/Card/ProductCard.vue
  frontend/src/components/Card/ProductCardMain.vue
  frontend/src/components/CautionBlock.vue
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/components/Form/PasswordInput.vue
  frontend/src/consts/dummy.js
  frontend/src/layouts/default/MainView.vue
  frontend/src/router/index.js
  frontend/src/views/DeliveryRegistView.vue
  frontend/src/views/EditProileView.vue
  frontend/src/views/HomeView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MypageView.vue
  frontend/src/views/ProductDetailsView.vue
  frontend/src/views/ProductsView.vue
  frontend/src/views/PurchaseRequestView.vue
  frontend/src/views/RegistProductView.vue
  frontend/src/views/SignupView.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#119 Fix: 체크박스 에러 해결
  frontend/src/components/CautionBlock.vue
  frontend/src/views/PurchaseRequestView.vue
Labels: 버그, UI/UX, 프론트엔드

#122 Chore: Docker nginx 설정 파일 추가
  frontend/Dockerfile
  frontend/docker/nginx.conf
Labels: 프론트엔드, 개발환경 세팅

#124 Fix: 구매하기 버튼 영역 확장
  frontend/src/views/ProductDetailsView.vue
Labels: 버그, UI/UX, 프론트엔드

#130 Refactor: 사용자 프로필 입력 폼 유효성 검사 추가
  frontend/src/views/EditProileView.vue
Labels: UI/UX, 프론트엔드, 리팩토링

#126 Design: 구매내역 상세 페이지 UI 구현
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/MypageView.vue
  frontend/src/views/PurchaseCompleteView.vue
Labels: UI/UX, 프론트엔드

#128 Chore: S3를 연동한다
  backend/build.gradle
  backend/src/main/java/com/easypeach/shroop/infra/s3/S3Config.java
  backend/src/main/java/com/easypeach/shroop/infra/s3/service/S3UploadService.java
Labels: 백엔드, 개발환경 세팅

#134 Feat: 신고 및 중재하기 API를 구현하다
  backend/src/docs/asciidoc/auth.adoc
  backend/src/main/java/com/easypeach/shroop/modules/global/response/BasicResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/report/controller/ReportController.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/Report.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImg.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportImgRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportRepostiory.java
  backend/src/main/java/com/easypeach/shroop/modules/report/domain/ReportStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/report/dto/ReportRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/report/dto/request/ReportRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportService.java
  backend/src/test/java/com/easypeach/shroop/modules/report/controller/ReportControllerTest.java
Labels: 기능개발, 백엔드

#139 Refactor: 신고하기 API에 S3을 연동한다
  backend/src/main/java/com/easypeach/shroop/modules/report/service/ReportImgService.java
Labels: 백엔드, 리팩토링

#142 Test: cicd jenkins test
  backend/README.md
Labels: 인프라

#143 Feat/137 test cicd infra
  backend/README.md
Labels: UI/UX, 프론트엔드, 테스트

#141 Feat/ 세션 기반 인증/인가 구현
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/AuthExceptionHandlerFilter.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/JsonUsernamePasswordAuthenticationFilter.java
  backend/src/main/java/com/easypeach/shroop/infra/security/filter/JwtAuthFilter.java
  backend/src/main/java/com/easypeach/shroop/infra/security/handler/SecurityAuthenticationEntryPoint.java
  backend/src/main/java/com/easypeach/shroop/infra/security/handler/SecurityAuthenticationFailureHandler.java
  backend/src/main/java/com/easypeach/shroop/infra/security/handler/SecurityAuthenticationSuccessHandler.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignInRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignUpRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/AccessTokenResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/LoginSuccessResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/SignUpCompletedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/JwtTokenProvider.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/SecurityUserDetailsService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/support/LoginMemberId.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/common/SecurityControllerTest.java
Labels: 기능개발, 백엔드, 리팩토링

#144 Feat/137 test cicd infra
  backend/README.md
Labels: UI/UX, 백엔드, 개발환경 세팅

#145 Feat/137 test cicd infra
  backend/README.md
Labels: UI/UX, 프론트엔드, 테스트

#146 Feat/137 test cicd infra
  backend/README.md
Labels: 프론트엔드, 개발환경 세팅, 테스트

#147 Feat/137 test cicd infra
  backend/README.md
Labels: 프론트엔드, 개발환경 세팅, 테스트

#152 Fix: allowCredentials 설정 변경하여 쿠키 인증 가능하도록 수정
  backend/src/main/java/com/easypeach/shroop/infra/config/WebConfig.java
Labels: 버그, 백엔드

#155 Refactor: 쿠키,세션에 맞는 로그인 정보로 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
Labels: 백엔드, 리팩토링

#157 Feat: axios API 요청에 사용할 컴포넌트 생성
  frontend/src/api/index.js
  frontend/src/api/modules/deleteApi.js
  frontend/src/api/modules/getApi.js
  frontend/src/api/modules/index.js
  frontend/src/api/modules/multipartPostApi.js
  frontend/src/api/modules/patchApi.js
  frontend/src/api/modules/postApi.js
Labels: 기능개발, 프론트엔드

#160 Feat: 상품 등급 및 상태 enum
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Grade.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductGrade.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductStatus.java
Labels: 기능개발, 백엔드

#162 Fix: Product의 Grade 필드명 수정
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
Labels: 버그, 백엔드

#159 Feat: 신고하기 API을 프론트서버에 연동한다
  frontend/src/api/index.js
  frontend/src/components/Button/SubmitButton.vue
  frontend/src/components/Form/data/formRules.js
  frontend/src/components/Modal/PlainModal.vue
  frontend/src/utils/index.js
  frontend/src/utils/multipartFormData.js
  frontend/src/views/ReportView.vue
Labels: 기능개발, 프론트엔드

#164 Feat: 로그인 API 연동
  frontend/src/views/LoginView.vue
Labels: 기능개발, 프론트엔드

#168 Feat: 문자발송 기능을 구현한다
  backend/build.gradle
  backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthClient.java
  backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/infra/phone/dto/MessageRequest.java
  backend/src/main/java/com/easypeach/shroop/infra/phone/dto/PhoneAuthResponse.java
  backend/src/main/java/com/easypeach/shroop/infra/phone/dto/SmsRequest.java
Labels: 기능개발, 백엔드

#167 Refactor: 상품 결제 API 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/TransactionCreateRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 백엔드, 리팩토링

#170 Feat: 아이디,닉네임,휴대전화 중복 검사 API 구현
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/controller/DuplicateValidController.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/DuplicateValidResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
Labels: 기능개발, 백엔드

#169 Feat: 상품 등록 API 구현
  backend/.gitignore
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/CategoryController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Category.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductGrade.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/CategoryResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductCreatedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/exception/CategoryNotFoundException.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/CategoryRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductImgRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/CategoryService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
Labels: 기능개발, 백엔드

#172 Feat: 결제 API 기능 추가(결제 시 상품 수정)
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionInfoResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 기능개발, 백엔드

#173 Feat: 결제 API 프론트 연동
  backend/src/main/resources/import.sql
  frontend/.gitignore
  frontend/src/views/PurchaseCompleteView.vue
  frontend/src/views/PurchaseRequestView.vue
Labels: 기능개발, 프론트엔드

#175 Feat: 알림 API을 구현한다
  backend/src/main/java/com/easypeach/shroop/infra/phone/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/controller/NotificationController.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/domain/Notification.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/domain/NotificationRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/dto/request/NotificationRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/dto/response/NotificationLinkResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/dto/response/NotificationResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/service/NotificationService.java
  backend/src/test/java/com/easypeach/shroop/modules/notification/controller/NotificationControllerTest.java
Labels: 기능개발, 백엔드

#181 Feat: 상품 결제 API 수정(IMG), 그에 맞게 프론트 연동
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionInfoResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  frontend/src/views/PurchaseCompleteView.vue
  frontend/src/views/PurchaseRequestView.vue
Labels: 기능개발, 프론트엔드, 백엔드

#182 Feat: 상품 수정 API를 구현한다
  backend/.gitignore
  backend/src/main/java/com/easypeach/shroop/infra/config/InitDb.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/CategoryController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/CategoryRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/CategoryResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/CategoryService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/main/resources/import.sql
Labels: 기능개발, 백엔드

#180 Refactor: 신고하기 API 테스트 코드를 리팩토링한다
  backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/report/controller/ReportControllerTest.java
Labels: 백엔드, 리팩토링, 테스트

#187 Feat: 상품 삭제 API 구현
  backend/.gitignore
  backend/src/main/java/com/easypeach/shroop/infra/config/InitDb.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/CategoryRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductCreatedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/exception/ProductException.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/CategoryRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/CategoryService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
Labels: 기능개발, 백엔드

#194 Refactor: 예외 처리 및 컨트롤러 리팩토링
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/SellerPurchaseException.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
Labels: 기능개발, 백엔드, 리팩토링

#185 Feat: 회원 가입 시 휴대전화 본인 인증 도입
  backend/src/main/java/com/easypeach/shroop/infra/phone/NaverPhoneAuthClient.java
  backend/src/main/java/com/easypeach/shroop/infra/phone/NaverPhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/domain/PhoneAuth.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/PhoneAuthRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/PhoneNumber.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/request/SignUpRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/PhoneAuthUUID.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/PhoneAuthFailException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/PhoneAuthNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/repository/PhoneAuthRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/SecurityUserDetailsService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Role.java
  backend/src/main/java/com/easypeach/shroop/modules/member/exception/MemberNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
  backend/src/test/java/com/easypeach/shroop/modules/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/common/ControllerTest.java
  backend/src/test/java/com/easypeach/shroop/modules/common/SecurityControllerTest.java
Labels: 기능개발, 백엔드

#186 Feat: 프론트 회원 가입 API 연동
  frontend/src/components/Form/CustomTextInput.vue
  frontend/src/components/Form/PhoneInput.vue
  frontend/src/components/Form/data/formRules.js
  frontend/src/router/index.js
  frontend/src/store/signUp.js
  frontend/src/views/PhoneAuthView.vue
  frontend/src/views/SignupView.vue
Labels: 기능개발, 프론트엔드

#200 Chore: 쿠키 라이브러리 의존성 추가
  frontend/package.json
Labels: 버그, 프론트엔드

#203 Feat: 로그인 여부를 알려주는 API 구현
  backend/src/main/java/com/easypeach/shroop/modules/auth/controller/AuthController.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/dto/response/LoginCheckResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/AuthService.java
Labels: 기능개발, 백엔드

#197 Feat: 프론트에 알림 API를 연동한다
  frontend/src/api/modules/index.js
  frontend/src/components/Button/NotifyBellButton.vue
  frontend/src/components/NotifyBar.vue
  frontend/src/layouts/default/AppBar.vue
  frontend/src/store/useCheckLogin.js
  frontend/src/store/useNotifyList.js
Labels: 기능개발, 프론트엔드

#201 Feat: 구매자 정보 조회 API를 구현한다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/BuyerResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/TransactionNotExistException.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 기능개발, 백엔드

#207 Fix: 구매자정보 조회 API 테스트 코드 오류를 수정한다
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 버그, 백엔드, 테스트

#209 Feat: 상품 결제 API 테스트 코드 작성 및 리팩토링을 한다.
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/TransactionCreatedResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 백엔드, 리팩토링, 테스트

#211 Feat: 상품 조회 api 구현
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/MemberRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/MemberResonse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductImgResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/exception/ProductException.java
  backend/src/main/java/com/easypeach/shroop/modules/product/exception/ProductImgLengthException.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductImgRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
Labels: 기능개발, 백엔드

#215 Feat: 로그인 API 연동
  frontend/.env.production
  frontend/src/App.vue
  frontend/src/api/index.js
  frontend/src/layouts/default/AppBar.vue
  frontend/src/store/useCheckLogin.js
  frontend/src/views/EditProileView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/PhoneAuthView.vue
Labels: 기능개발, 프론트엔드

#216 Feat: 반품하기 API를 구현한다
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductReturnController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturn.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/ProductReturnImg.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductReturnRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnImgRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductReturnRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductReturnControllerTest.java
Labels: 기능개발, 백엔드

#220 Fix: 반품하기 API 테스트 코드 수정을 수정한다
  backend/src/test/java/com/easypeach/shroop/modules/product/controller/ProductReturnControllerTest.java
Labels: 버그, 백엔드

#218 Feat: 구매 취소하기 API를 구현한다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 기능개발, 백엔드

#225 Feat: 구매 확정하기 API를 구현한다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/IsNotBuyerException.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 기능개발, 백엔드

#222 Feat: logout 호출 시 세션에서 사용자 로그인 정보 제거
  backend/src/main/java/com/easypeach/shroop/infra/security/SecurityConfig.java
Labels: 기능개발, 백엔드

#227 Feat: 반품 확정하기 API를 구현한다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/exception/IsNotSellerException.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionControllerTest.java
Labels: 기능개발, 백엔드

#230 Refactor: 판매내역 API를 수정한다
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/TransactionStatus.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/main/resources/import.sql
  frontend/src/consts/status.js
Labels: 프론트엔드, 백엔드, 리팩토링

#239 Fix: status 변경에 따른 코드 수정
  backend/src/main/resources/import.sql
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryControllerTest.java
  frontend/package-lock.json
  frontend/src/components/Banner/MypageProductBanner.vue
Labels: 버그, 프론트엔드, 백엔드

#236 Feat: 프론트에 구매 취소하기 API를 연동한다
  frontend/src/components/Banner/MypageProductBanner.vue
Labels: 기능개발, 프론트엔드

#233 Refactor: product response service에 판매자 set 추가
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/request/ProductRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
Labels: 백엔드, 리팩토링

#247 Fix: 인증번호 확인 화면 라우터 체크에서 제외
  frontend/src/App.vue
  frontend/src/views/SignupView.vue
Labels: 버그, 백엔드

#248 Feat: 판매내역 & 구매내역 API를 마이페이지에서 호출했다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/HistoryResponse.java
  frontend/src/components/Banner/MypageProductBanner.vue
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/consts/status.js
  frontend/src/views/MypageView.vue
  frontend/src/views/PurchaseRequestView.vue
Labels: 기능개발, 프론트엔드, 백엔드

#234 Feat: 프론트에 반품 신청하기 API를 연동한다
  frontend/src/components/Form/CustomTextArea.vue
  frontend/src/views/ReturnRequestView.vue
Labels: 기능개발, 프론트엔드

#245 Refactor: 생성일자 내림차순으로 알림 리스트를 반환하도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/notification/domain/NotificationRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/notification/service/NotificationService.java
Labels: 백엔드, 리팩토링

#242 Refactor: 반품 신청시 알림가도록 수정했다
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductReturnService.java
Labels: 백엔드, 리팩토링

#255 Feat: 프론트에 구매 확정하기 API를 연동한다
  frontend/src/components/Banner/MypageProductBanner.vue
Labels: 기능개발, 프론트엔드

#257 Feat: 프론트에 반품 확정하기 API를 연동한다
  frontend/src/components/Banner/MypageProductBanner.vue
Labels: 기능개발, 프론트엔드

#258 Feat: 택배 등록하기 API를 구현한다
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/DeliveryController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Delivery.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/DeliveryRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/domain/Transaction.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/request/DeliveryRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/DeliveryService.java
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/DeliveryControllerTest.java
Labels: 기능개발, 백엔드

#253 Fix: 모달 취소 핸들러 추가 구현
  frontend/src/views/ProductDetailsView.vue
Labels: 버그, 프론트엔드

#251 Feat: 회원 프로필 API 구현
  backend/src/main/java/com/easypeach/shroop/modules/auth/exception/InvalidTokenException.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/repository/PhoneAuthRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/auth/service/PhoneAuthService.java
  backend/src/main/java/com/easypeach/shroop/modules/global/exception/ExceptionControllerAdvice.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/DuplicateValidController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/controller/MemberController.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/DuplicateCheckType.java
  backend/src/main/java/com/easypeach/shroop/modules/member/domain/Member.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/reponse/ProfileEditForm.java
  backend/src/main/java/com/easypeach/shroop/modules/member/dto/request/ProfileEditRequest.java
  backend/src/main/java/com/easypeach/shroop/modules/member/exception/DuplicateValueException.java
  backend/src/main/java/com/easypeach/shroop/modules/member/exception/PasswordNotMatchException.java
  backend/src/main/java/com/easypeach/shroop/modules/member/service/MemberService.java
Labels: 기능개발, 백엔드

#263 Feat: 좋아요 API 구현
  backend/src/main/java/com/easypeach/shroop/modules/like/controller/LikeController.java
  backend/src/main/java/com/easypeach/shroop/modules/like/domain/LikeRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/like/service/LikeService.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/controller/LikeController.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/domain/LikeRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/domain/Likes.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/exception/LikesProductNotFoundException.java
  backend/src/main/java/com/easypeach/shroop/modules/likes/service/LikeService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/CategoryController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/controller/ProductController.java
  backend/src/main/java/com/easypeach/shroop/modules/product/domain/Product.java
  backend/src/main/java/com/easypeach/shroop/modules/product/dto/response/ProductResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/CategoryService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductImgService.java
  backend/src/main/java/com/easypeach/shroop/modules/product/service/ProductService.java
  backend/src/test/java/com/easypeach/shroop/modules/likes/controller/LikeControllerTest.java
Labels: 기능개발, 백엔드

#264 Feat: 배송등록 API 연동
  frontend/src/views/DeliveryRegistView.vue
Labels: 기능개발, 프론트엔드

#261 Feat: 내역 API 프론트 연동
  backend/src/main/java/com/easypeach/shroop/modules/product/respository/ProductRepository.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryController.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/dto/response/PageResponse.java
  backend/src/main/java/com/easypeach/shroop/modules/transaction/service/TransactionService.java
  backend/src/main/resources/import.sql
  backend/src/test/java/com/easypeach/shroop/modules/transaction/controller/TransactionHistoryControllerTest.java
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/views/MypageView.vue
Labels: 프론트엔드, 백엔드, 리팩토링

#267 Feat: 프로필 수정 API 연동
  frontend/src/views/EditProileView.vue
Labels: 기능개발, 프론트엔드

#272 Feat: 좋아요 API 프론트에 적용
  frontend/src/components/Badge/TransactionBadge.vue
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Button/LikeButton.vue
  frontend/src/components/Card/ProductCard.vue
  frontend/src/layouts/ContentLayout.vue
  frontend/src/utils/index.js
  frontend/src/utils/toggleLikesProduct.js
  frontend/src/views/HomeView.vue
  frontend/src/views/ProductDetailsView.vue
  frontend/src/views/ProductsView.vue
Labels: 기능개발, 프론트엔드

#274 Remove: env.production 제거
  frontend/.env.production
Labels: 프론트엔드, 개발환경 세팅

#276 Fix: 상품 카드 좋아요 클릭시 예외처리 안해주는 버그 수정
  frontend/src/views/HomeView.vue
  frontend/src/views/ProductsView.vue
Labels: 버그, 프론트엔드

#278 Fix: 구매하기 화면에서 거래완료 뱃지를 제거한다
  frontend/src/components/Banner/ProductBanner.vue
  frontend/src/components/Button/LikeButton.vue
  frontend/src/components/Form/CustomTextArea.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/ProductDetailsView.vue
  frontend/src/views/PurchaseCompleteView.vue
  frontend/src/views/RegistProductView.vue
Labels: 버그, 프론트엔드
